# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options

          # https://github.com/lowlighter/metrics/tree/master/source/plugins/core
          # https://github.com/lowlighter/metrics/tree/master/source/plugins/base
          user: nason
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_affiliations: owner, collaborator
          config_timezone: America/New_York
          # output_condition: data-changed
          # plugins_errors_fatal: yes

          # https://github.com/lowlighter/metrics/tree/master/source/plugins/isocalendar
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/habits
          # plugin_habits: yes
          # plugin_habits_days: 30
          # plugin_habits_from: 1000
          # plugin_habits_facts: yes
          # plugin_habits_charts: yes
          # plugin_habits_trim: yes          

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/stars
          plugin_stars: yes